### ISSUE TITLE
Module not found: 'net-keepalive'

### ISSUE THREAD

**Issue by baughmann** [pkoretic/json_rpc#3]
I'm getting this error in the terminal:

```
Warning in ./~/json-rpc-client/lib/jsonrpc.js
Module not found: 'net-keepalive' in /home/nbaughman/Projects/Firebase/RCS/node_modules/json-rpc-client/lib

@ ./~/json-rpc-client/lib/jsonrpc.js 151:42-66
```

Resulting in Chrome giving me:
`TypeError: net.connect is not a function(…)`

From the following line in my App.js:

`const client = new jsonrpc({ port: 55552, host: '127.0.0.1'})`

Any ideas?

**Comment by pkoretic** [comment]
hm, it should be optional, let me take a look, you can try to install it manually

```
npm install net-keepalive
```

**Comment by baughmann** [comment]
I did that as well actually and was then getting some errors from
net-keepalive about unexpected token '@'

**Comment by pkoretic** [comment]
@nickdb93 Sorry for the late response.
How exactly are you running this in Chrome?
Do you use it for backend in Node.js or what is your usage?

**Comment by baughmann** [comment]
I'm sorry for the even later response. I got deployed and life got in the way. Thank you for the assist.
